apiVersion: v1
kind: Service
metadata:
  name: kube-lab-service
spec:
  type: NodePort
  selector:
    app: kube-lab  # Update this to match your deployment's labels
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP